INSERT INTO PAIS VALUES('AF', 'Afganistán');
INSERT INTO PAIS VALUES('AX', 'Islas Gland');
INSERT INTO PAIS VALUES('AL', 'Albania');
INSERT INTO PAIS VALUES('DE', 'Alemania');
INSERT INTO PAIS VALUES('AD', 'Andorra');
INSERT INTO PAIS VALUES('AO', 'Angola');
INSERT INTO PAIS VALUES('AI', 'Anguilla');
INSERT INTO PAIS VALUES('AQ', 'Antártida');
INSERT INTO PAIS VALUES('AG', 'Antigua y Barbuda');
INSERT INTO PAIS VALUES( 'AN', 'Antillas Holandesas');
INSERT INTO PAIS VALUES( 'SA', 'Arabia Saudí');
INSERT INTO PAIS VALUES( 'DZ', 'Argelia');
INSERT INTO PAIS VALUES( 'AR', 'Argentina');
INSERT INTO PAIS VALUES( 'AM', 'Armenia');
INSERT INTO PAIS VALUES( 'AW', 'Aruba');
INSERT INTO PAIS VALUES( 'AU', 'Australia');
INSERT INTO PAIS VALUES( 'AT', 'Austria');
INSERT INTO PAIS VALUES( 'AZ', 'Azerbaiyán');
INSERT INTO PAIS VALUES( 'BS', 'Bahamas');
INSERT INTO PAIS VALUES( 'BH', 'Bahréin');
INSERT INTO PAIS VALUES( 'BD', 'Bangladesh');
INSERT INTO PAIS VALUES( 'BB', 'Barbados');
INSERT INTO PAIS VALUES( 'BY', 'Bielorrusia');
INSERT INTO PAIS VALUES( 'BE', 'Bélgica');
INSERT INTO PAIS VALUES( 'BZ', 'Belice');
INSERT INTO PAIS VALUES( 'BJ', 'Benin');
INSERT INTO PAIS VALUES( 'BM', 'Bermudas');
INSERT INTO PAIS VALUES( 'BT', 'Bhután');
INSERT INTO PAIS VALUES( 'BO', 'Bolivia');
INSERT INTO PAIS VALUES( 'BA', 'Bosnia y Herzegovina');
INSERT INTO PAIS VALUES( 'BW', 'Botsuana');
INSERT INTO PAIS VALUES( 'BV', 'Isla Bouvet');
INSERT INTO PAIS VALUES( 'BR', 'Brasil');
INSERT INTO PAIS VALUES( 'BN', 'Brunéi');
INSERT INTO PAIS VALUES( 'BG', 'Bulgaria');
INSERT INTO PAIS VALUES( 'BF', 'Burkina Faso');
INSERT INTO PAIS VALUES( 'BI', 'Burundi');
INSERT INTO PAIS VALUES( 'CV', 'Cabo Verde');
INSERT INTO PAIS VALUES( 'KY', 'Islas Caimán');
INSERT INTO PAIS VALUES( 'KH', 'Camboya');
INSERT INTO PAIS VALUES( 'CM', 'Camerún');
INSERT INTO PAIS VALUES( 'CA', 'Canadá');
INSERT INTO PAIS VALUES( 'CF', 'República Centroafricana');
INSERT INTO PAIS VALUES( 'TD', 'Chad');
INSERT INTO PAIS VALUES( 'CZ', 'República Checa');
INSERT INTO PAIS VALUES( 'CL', 'Chile');
INSERT INTO PAIS VALUES( 'CN', 'China');
INSERT INTO PAIS VALUES( 'CY', 'Chipre');
INSERT INTO PAIS VALUES( 'CX', 'Isla de Navidad');
INSERT INTO PAIS VALUES( 'VA', 'Ciudad del Vaticano');
INSERT INTO PAIS VALUES( 'CC', 'Islas Cocos');
INSERT INTO PAIS VALUES( 'CO', 'Colombia');
INSERT INTO PAIS VALUES( 'KM', 'Comoras');
INSERT INTO PAIS VALUES( 'CD', 'República Democrática del Congo');
INSERT INTO PAIS VALUES( 'CG', 'Congo');
INSERT INTO PAIS VALUES( 'CK', 'Islas Cook');
INSERT INTO PAIS VALUES( 'KP', 'Corea del Norte');
INSERT INTO PAIS VALUES( 'KR', 'Corea del Sur');
INSERT INTO PAIS VALUES( 'CI', 'Costa de Marfil');
INSERT INTO PAIS VALUES( 'CR', 'Costa Rica');
INSERT INTO PAIS VALUES( 'HR', 'Croacia');
INSERT INTO PAIS VALUES( 'CU', 'Cuba');
INSERT INTO PAIS VALUES( 'DK', 'Dinamarca');
INSERT INTO PAIS VALUES( 'DM', 'Dominica');
INSERT INTO PAIS VALUES( 'DO', 'República Dominicana');
INSERT INTO PAIS VALUES( 'EC', 'Ecuador');
INSERT INTO PAIS VALUES( 'EG', 'Egipto');
INSERT INTO PAIS VALUES( 'SV', 'El Salvador');
INSERT INTO PAIS VALUES( 'AE', 'Emiratos Árabes Unidos');
INSERT INTO PAIS VALUES( 'ER', 'Eritrea');
INSERT INTO PAIS VALUES( 'SK', 'Eslovaquia');
INSERT INTO PAIS VALUES( 'SI', 'Eslovenia');
INSERT INTO PAIS VALUES( 'ES', 'España');
INSERT INTO PAIS VALUES( 'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO PAIS VALUES( 'US', 'Estados Unidos');
INSERT INTO PAIS VALUES( 'EE', 'Estonia');
INSERT INTO PAIS VALUES( 'ET', 'Etiopía');
INSERT INTO PAIS VALUES( 'FO', 'Islas Feroe');
INSERT INTO PAIS VALUES( 'PH', 'Filipinas');
INSERT INTO PAIS VALUES( 'FI', 'Finlandia');
INSERT INTO PAIS VALUES( 'FJ', 'Fiyi');
INSERT INTO PAIS VALUES( 'FR', 'Francia');
INSERT INTO PAIS VALUES( 'GA', 'Gabón');
INSERT INTO PAIS VALUES( 'GM', 'Gambia');
INSERT INTO PAIS VALUES( 'GE', 'Georgia');
INSERT INTO PAIS VALUES( 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO PAIS VALUES( 'GH', 'Ghana');
INSERT INTO PAIS VALUES( 'GI', 'Gibraltar');
INSERT INTO PAIS VALUES( 'GD', 'Granada');
INSERT INTO PAIS VALUES( 'GR', 'Grecia');
INSERT INTO PAIS VALUES( 'GL', 'Groenlandia');
INSERT INTO PAIS VALUES( 'GP', 'Guadalupe');
INSERT INTO PAIS VALUES( 'GU', 'Guam');
INSERT INTO PAIS VALUES( 'GT', 'Guatemala');
INSERT INTO PAIS VALUES( 'GF', 'Guayana Francesa');
INSERT INTO PAIS VALUES( 'GN', 'Guinea');
INSERT INTO PAIS VALUES( 'GQ', 'Guinea Ecuatorial');
INSERT INTO PAIS VALUES( 'GW', 'Guinea-Bissau');
INSERT INTO PAIS VALUES( 'GY', 'Guyana');
INSERT INTO PAIS VALUES( 'HT', 'Haití');
INSERT INTO PAIS VALUES( 'HM', 'Islas Heard y McDonald');
INSERT INTO PAIS VALUES( 'HN', 'Honduras');
INSERT INTO PAIS VALUES( 'HK', 'Hong Kong');
INSERT INTO PAIS VALUES( 'HU', 'Hungría');
INSERT INTO PAIS VALUES( 'IN', 'India');
INSERT INTO PAIS VALUES( 'ID', 'Indonesia');
INSERT INTO PAIS VALUES( 'IR', 'Irán');
INSERT INTO PAIS VALUES( 'IQ', 'Iraq');
INSERT INTO PAIS VALUES( 'IE', 'Irlanda');
INSERT INTO PAIS VALUES( 'IS', 'Islandia');
INSERT INTO PAIS VALUES( 'IL', 'Israel');
INSERT INTO PAIS VALUES( 'IT', 'Italia');
INSERT INTO PAIS VALUES( 'JM', 'Jamaica');
INSERT INTO PAIS VALUES( 'JP', 'Japón');
INSERT INTO PAIS VALUES( 'JO', 'Jordania');
INSERT INTO PAIS VALUES( 'KZ', 'Kazajstán');
INSERT INTO PAIS VALUES( 'KE', 'Kenia');
INSERT INTO PAIS VALUES( 'KG', 'Kirguistán');
INSERT INTO PAIS VALUES( 'KI', 'Kiribati');
INSERT INTO PAIS VALUES( 'KW', 'Kuwait');
INSERT INTO PAIS VALUES( 'LA', 'Laos');
INSERT INTO PAIS VALUES( 'LS', 'Lesotho');
INSERT INTO PAIS VALUES( 'LV', 'Letonia');
INSERT INTO PAIS VALUES( 'LB', 'Líbano');
INSERT INTO PAIS VALUES( 'LR', 'Liberia');
INSERT INTO PAIS VALUES( 'LY', 'Libia');
INSERT INTO PAIS VALUES( 'LI', 'Liechtenstein');
INSERT INTO PAIS VALUES( 'LT', 'Lituania');
INSERT INTO PAIS VALUES( 'LU', 'Luxemburgo');
INSERT INTO PAIS VALUES( 'MO', 'Macao');
INSERT INTO PAIS VALUES( 'MK', 'ARY Macedonia');
INSERT INTO PAIS VALUES( 'MG', 'Madagascar');
INSERT INTO PAIS VALUES( 'MY', 'Malasia');
INSERT INTO PAIS VALUES( 'MW', 'Malawi');
INSERT INTO PAIS VALUES( 'MV', 'Maldivas');
INSERT INTO PAIS VALUES( 'ML', 'Malí');
INSERT INTO PAIS VALUES( 'MT', 'Malta');
INSERT INTO PAIS VALUES( 'FK', 'Islas Malvinas');
INSERT INTO PAIS VALUES( 'MP', 'Islas Marianas del Norte');
INSERT INTO PAIS VALUES( 'MA', 'Marruecos');
INSERT INTO PAIS VALUES( 'MH', 'Islas Marshall');
INSERT INTO PAIS VALUES( 'MQ', 'Martinica');
INSERT INTO PAIS VALUES( 'MU', 'Mauricio');
INSERT INTO PAIS VALUES( 'MR', 'Mauritania');
INSERT INTO PAIS VALUES( 'YT', 'Mayotte');
INSERT INTO PAIS VALUES( 'MX', 'México');
INSERT INTO PAIS VALUES( 'FM', 'Micronesia');
INSERT INTO PAIS VALUES( 'MD', 'Moldavia');
INSERT INTO PAIS VALUES( 'MC', 'Mónaco');
INSERT INTO PAIS VALUES( 'MN', 'Mongolia');
INSERT INTO PAIS VALUES( 'MS', 'Montserrat');
INSERT INTO PAIS VALUES( 'MZ', 'Mozambique');
INSERT INTO PAIS VALUES( 'MM', 'Myanmar');
INSERT INTO PAIS VALUES( 'NA', 'Namibia');
INSERT INTO PAIS VALUES( 'NR', 'Nauru');
INSERT INTO PAIS VALUES( 'NP', 'Nepal');
INSERT INTO PAIS VALUES( 'NI', 'Nicaragua');
INSERT INTO PAIS VALUES( 'NE', 'Níger');
INSERT INTO PAIS VALUES( 'NG', 'Nigeria');
INSERT INTO PAIS VALUES( 'NU', 'Niue');
INSERT INTO PAIS VALUES( 'NF', 'Isla Norfolk');
INSERT INTO PAIS VALUES( 'NO', 'Noruega');
INSERT INTO PAIS VALUES( 'NC', 'Nueva Caledonia');
INSERT INTO PAIS VALUES( 'NZ', 'Nueva Zelanda');
INSERT INTO PAIS VALUES( 'OM', 'Omán');
INSERT INTO PAIS VALUES( 'NL', 'Países Bajos');
INSERT INTO PAIS VALUES( 'PK', 'Pakistán');
INSERT INTO PAIS VALUES( 'PW', 'Palau');
INSERT INTO PAIS VALUES( 'PS', 'Palestina');
INSERT INTO PAIS VALUES( 'PA', 'Panamá');
INSERT INTO PAIS VALUES( 'PG', 'Papúa Nueva Guinea');
INSERT INTO PAIS VALUES( 'PY', 'Paraguay');
INSERT INTO PAIS VALUES( 'PE', 'Perú');
INSERT INTO PAIS VALUES( 'PN', 'Islas Pitcairn');
INSERT INTO PAIS VALUES( 'PF', 'Polinesia Francesa');
INSERT INTO PAIS VALUES( 'PL', 'Polonia');
INSERT INTO PAIS VALUES( 'PT', 'Portugal');
INSERT INTO PAIS VALUES( 'PR', 'Puerto Rico');
INSERT INTO PAIS VALUES( 'QA', 'Qatar');
INSERT INTO PAIS VALUES( 'GB', 'Reino Unido');
INSERT INTO PAIS VALUES( 'RE', 'Reunión');
INSERT INTO PAIS VALUES( 'RW', 'Ruanda');
INSERT INTO PAIS VALUES( 'RO', 'Rumania');
INSERT INTO PAIS VALUES( 'RU', 'Rusia');
INSERT INTO PAIS VALUES( 'EH', 'Sahara Occidental');
INSERT INTO PAIS VALUES( 'SB', 'Islas Salomón');
INSERT INTO PAIS VALUES( 'WS', 'Samoa');
INSERT INTO PAIS VALUES( 'AS', 'Samoa Americana');
INSERT INTO PAIS VALUES( 'KN', 'San Cristóbal y Nevis');
INSERT INTO PAIS VALUES( 'SM', 'San Marino');
INSERT INTO PAIS VALUES( 'PM', 'San Pedro y Miquelón');
INSERT INTO PAIS VALUES( 'VC', 'San Vicente y las Granadinas');
INSERT INTO PAIS VALUES( 'SH', 'Santa Helena');
INSERT INTO PAIS VALUES( 'LC', 'Santa Lucía');
INSERT INTO PAIS VALUES( 'ST', 'Santo Tomé y Príncipe');
INSERT INTO PAIS VALUES( 'SN', 'Senegal');
INSERT INTO PAIS VALUES( 'CS', 'Serbia y Montenegro');
INSERT INTO PAIS VALUES( 'SC', 'Seychelles');
INSERT INTO PAIS VALUES( 'SL', 'Sierra Leona');
INSERT INTO PAIS VALUES( 'SG', 'Singapur');
INSERT INTO PAIS VALUES( 'SY', 'Siria');
INSERT INTO PAIS VALUES( 'SO', 'Somalia');
INSERT INTO PAIS VALUES( 'LK', 'Sri Lanka');
INSERT INTO PAIS VALUES( 'SZ', 'Suazilandia');
INSERT INTO PAIS VALUES( 'ZA', 'Sudáfrica');
INSERT INTO PAIS VALUES( 'SD', 'Sudán');
INSERT INTO PAIS VALUES( 'SE', 'Suecia');
INSERT INTO PAIS VALUES( 'CH', 'Suiza');
INSERT INTO PAIS VALUES( 'SR', 'Surinam');
INSERT INTO PAIS VALUES( 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO PAIS VALUES( 'TH', 'Tailandia');
INSERT INTO PAIS VALUES( 'TW', 'Taiwán');
INSERT INTO PAIS VALUES( 'TZ', 'Tanzania');
INSERT INTO PAIS VALUES( 'TJ', 'Tayikistán');
INSERT INTO PAIS VALUES( 'IO', 'Territorio Británico del Océano Índico');
INSERT INTO PAIS VALUES( 'TF', 'Territorios Australes Franceses');
INSERT INTO PAIS VALUES( 'TL', 'Timor Oriental');
INSERT INTO PAIS VALUES( 'TG', 'Togo');
INSERT INTO PAIS VALUES( 'TK', 'Tokelau');
INSERT INTO PAIS VALUES( 'TO', 'Tonga');
INSERT INTO PAIS VALUES( 'TT', 'Trinidad y Tobago');
INSERT INTO PAIS VALUES( 'TN', 'Túnez');
INSERT INTO PAIS VALUES( 'TC', 'Islas Turcas y Caicos');
INSERT INTO PAIS VALUES( 'TM', 'Turkmenistán');
INSERT INTO PAIS VALUES( 'TR', 'Turquía');
INSERT INTO PAIS VALUES( 'TV', 'Tuvalu');
INSERT INTO PAIS VALUES( 'UA', 'Ucrania');
INSERT INTO PAIS VALUES( 'UG', 'Uganda');
INSERT INTO PAIS VALUES( 'UY', 'Uruguay');
INSERT INTO PAIS VALUES( 'UZ', 'Uzbekistán');
INSERT INTO PAIS VALUES( 'VU', 'Vanuatu');
INSERT INTO PAIS VALUES( 'VE', 'Venezuela');
INSERT INTO PAIS VALUES( 'VN', 'Vietnam');
INSERT INTO PAIS VALUES( 'VG', 'Islas Vírgenes Británicas');
INSERT INTO PAIS VALUES( 'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO PAIS VALUES( 'WF', 'Wallis y Futuna');
INSERT INTO PAIS VALUES( 'YE', 'Yemen');
INSERT INTO PAIS VALUES( 'DJ', 'Yibuti');
INSERT INTO PAIS VALUES( 'ZM', 'Zambia');
INSERT INTO PAIS VALUES( 'ZW', 'Zimbabue');
 
 

INSERT INTO ESTIL (EST_NOM)
  VALUES ('trap');
  
INSERT INTO ESTIL (EST_NOM)
  VALUES ('rock');

INSERT INTO ESTIL (EST_NOM)
  VALUES ('pop');
  
 
 INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
      VALUES ('duki','I');
      
 INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
      VALUES ('Kidd Keo','I');
      
 INSERT INTO ARTISTA (ART_NOM , ART_TIPUS)
      VALUES ('C.R.O','I');
      
 INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
      VALUES ('Dua Lipa','I');
      
 INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
      VALUES ('Harry Styles','I');
      
 INSERT INTO ARTISTA (ART_NOM , ART_TIPUS)
      VALUES ('Veintiuno','I');
      
		
  INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
	  VALUES ('Bon Scott','I');

  INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
	  VALUES ('Angus Young','I');
	  
  INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
	  VALUES ('John Lenno','I');
	  
  INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
	  VALUES ('Ringo Starr','I');
	  
	  
	  
 INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
      VALUES ('ACDC','G');
      
  INSERT INTO ARTISTA ( ART_NOM , ART_TIPUS)
      VALUES ('The Beatles','G');

INSERT INTO ART_GRUP VALUES (7,DATE '2015-12-17');
INSERT INTO ART_GRUP VALUES (8,DATE '2016-05-10');


INSERT INTO ART_IND VALUES (1,DATE '1995-09-16','ES');
INSERT INTO ART_IND VALUES (2,DATE '2005-03-13','AR');
INSERT INTO ART_IND VALUES (3,DATE '2003-04-14','AR');
INSERT INTO ART_IND VALUES (4,DATE '2019-02-12','AR');
INSERT INTO ART_IND VALUES (5,DATE '2011-01-01','AU');
INSERT INTO ART_IND VALUES (6,DATE '2013-11-25','FR');
INSERT INTO ART_IND VALUES (7,DATE '1999-01-06','AM');
INSERT INTO ART_IND VALUES (8,DATE '1995-03-12','AM');
INSERT INTO ART_IND VALUES (9,DATE '1940-07-14','AM');
INSERT INTO ART_IND VALUES (10,DATE '1945-08-15','AM');


INSERT INTO H_GRUP VALUES (7,7,DATE '2003-05-06',NULL);
INSERT INTO H_GRUP VALUES (7,8,DATE '2003-05-06',NULL);

INSERT INTO H_GRUP VALUES (8,9,DATE '2003-05-06',DATE '1970-03-05');
INSERT INTO H_GRUP VALUES (8,10,DATE '2003-05-06',DATE '1970-03-05');





INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Ma Vie','N',1,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('GIVENCHY','N',1,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Hijo de la noche','N',1,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Thunderstruck','N',2,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Highway to Hell','N',2,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Beating Around the Bush','N',2,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Shot Down in Flames','N',2,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Get It Hot','N',2,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Night Prowler','N',2,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Dear Prudence','S',3,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Glass Onion','N',3,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Wild Honey Pie','S',3,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Happiness is a Warm Gun','N',3,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Back in the U.S.S.R.','N',3,'C');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Birthday','N',3,'C');

INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('All Together Now','N',3,'A');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Power Up','N',2,'A');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('llistos','N',1,'L');
INSERT INTO CATALEG (CAT_TITOL,CAT_ACTIU,CAT_ESTIL,CAT_TIPUS)  VALUES('Los mas virales','N',1,'L');


INSERT INTO CANÇO VALUES (1,DATE '2020-01-03',1,4);
INSERT INTO CANÇO VALUES (2,DATE '2020-08-15',2,3);
INSERT INTO CANÇO VALUES (3,DATE '2018-06-23',3,3);
INSERT INTO CANÇO VALUES (4,DATE '2018-06-23',4,2);
INSERT INTO CANÇO VALUES (5,DATE '2018-06-23',5,3);
INSERT INTO CANÇO VALUES (6,DATE '2018-06-23',6,5);
INSERT INTO CANÇO VALUES (7,DATE '2018-06-23',7,3);
INSERT INTO CANÇO VALUES (8,DATE '2018-06-23',8,2);
INSERT INTO CANÇO VALUES (9,DATE '2018-06-23',9,2);
INSERT INTO CANÇO VALUES (10,DATE '2018-06-23',10,4);
INSERT INTO CANÇO VALUES (11,DATE '2018-06-23',5,2);
INSERT INTO CANÇO VALUES (12,DATE '2018-06-23',6,3);
INSERT INTO CANÇO VALUES (13,DATE '2018-06-23',7,2);
INSERT INTO CANÇO VALUES (14,DATE '2018-06-23',8,4);
INSERT INTO CANÇO VALUES (15,DATE '2018-06-23',9,2);





INSERT INTO AUTORIA VALUES (2,1);
INSERT INTO AUTORIA VALUES (1,2);



INSERT INTO ALBUM VALUES (17,DATE '2005-02-12',12);
INSERT INTO ALBUM VALUES (16,DATE '2020-03-12',42);


INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO) VALUES (17,9);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (17,10);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (17,11);
INSERT INTO ALBUM_CONTINGUT(ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (17,12);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (17,13);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (17,14);

INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (16,3);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (16,4);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (16,5);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (16,6);
INSERT INTO ALBUM_CONTINGUT	(ALCO_ID_ALBUM,ALCO_ID_CANÇO) VALUES (16,7);
INSERT INTO ALBUM_CONTINGUT (ALCO_ID_ALBUM,ALCO_ID_CANÇO)VALUES (16,8);


INSERT INTO LLISTA VALUES(19,20);
INSERT INTO LLISTA VALUES(18,30);



INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,3);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,4);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,5);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,6);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,7);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,8);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,13);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(19,14);
							
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,9);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,10);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,11);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,12);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,13);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,14);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,5);
INSERT INTO LLISTA_CONTINGUT (LLCON_ID_LLISTA,LLCON_ID_CATALAG) VALUES(18,6);


INSERT INTO CLIENT VALUES (0,'virtual@gmail.com','virtual','virtual',DATE '2022-09-19',08700,'virtual',NULL,'igualada','ES');
INSERT INTO CLIENT VALUES (null,'jordi@gmail.com','jordi','valldaura',DATE '2003-01-08',08700,'passeig bardager',NULL,'igualada','ES');
INSERT INTO CLIENT VALUES (null,'arnau@gmail.com','arnua','romero',DATE '2005-04-09',08788,'carrer sant jaume ',NULL,'vilanova del cami','ES');


INSERT INTO REPRODUCIO VALUES (00,DATE '2022-09-19',18);
INSERT INTO REPRODUCIO VALUES (00,DATE '2022-09-19',16);
INSERT INTO REPRODUCIO VALUES (00,DATE '2022-09-19',1);


INSERT INTO REPRODUCIO VALUES (01,DATE '2022-09-19',18);
INSERT INTO REPRODUCIO VALUES (01,DATE '2022-09-19',17);
INSERT INTO REPRODUCIO VALUES (01,DATE '2022-09-19',4);


INSERT INTO REPRODUCIO VALUES (02,DATE '2022-09-19',15);
INSERT INTO REPRODUCIO VALUES (02,DATE '2022-09-19',17);
INSERT INTO REPRODUCIO VALUES (02,DATE '2022-09-19',8);


